### ISSUE TITLE
[Bug]: `act` import is deprecated.

### ISSUE THREAD

**Issue by ssm951** [cloudscape-design/test-utils#54]
### Package version

v3.0.0

### node-versions

v18

### Description

With an update to react dom test utils, the following warning is now given:
```
console.error
    Warning: `ReactDOMTestUtils.act` is deprecated in favor of `React.act`. Import `act` from `react` instead of `react-dom/test-utils`. See https://react.dev/warnings/react-dom-test-utils for more info.

      16 |     expectToBeTruthy(button);
      17 |     act(() => {
    > 18 |       button.click();
         |              ^
      19 |     });
      20 |     expect(container).toBeTruthy();
      21 |   });

      at printWarning (node_modules/react-dom/cjs/react-dom-test-utils.development.js:71:30)
      at error (node_modules/react-dom/cjs/react-dom-test-utils.development.js:45:7)
      at actWithWarning (node_modules/react-dom/cjs/react-dom-test-utils.development.js:1736:7)
      at ButtonWrapper.AbstractWrapper.fireEvent (node_modules/@amzn/awsui-test-utils-core/dist/dom.js:71:29)
      at ButtonWrapper.fireEvent [as click] (node_modules/@amzn/awsui-test-utils-core/dist/dom.js:55:14)
      at test/components/SearchButtonReset.test.tsx:18:14
      at node_modules/@testing-library/react/dist/act-compat.js:48:24
      at act (node_modules/react/cjs/react.development.js:2512:16)
      at node_modules/@testing-library/react/dist/act-compat.js:47:25
      ...
```
Looking at the source code, I can confirm that the deprecated import is here: https://github.com/cloudscape-design/test-utils/blob/74a10452b48d64902fe3a9b4044cf727b99c7caa/src/core/dom.ts#L4

Making a one line change as described in the URL referenced in the error log should fix this.

This doesn't break any of our tests yet, but it is adding a lot of error logs to our build and will eventually cause issues in the future.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/cloudscape-design/test-utils/blob/main/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/cloudscape-design/test-utils/issues) for duplicate problems

**Comment by rubencarvalho** [comment]
Hello, thank you for opening the issue. We have fixed in https://github.com/cloudscape-design/test-utils/pull/55.
